version = "3.11.5"
runner.dialect = scala3

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}

maxColumn = 100
newlines.source = keep
align.preset = more
docstrings.style = Asterisk

rewrite.scala3.convertToNewSyntax = false
rewrite.scala3.removeOptionalBraces = false